[package]
name = "tftp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-io = "2.3.3"
log = "0.4.22"
rand = "0.8.5"
tempdir = "0.3.7"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.4"

